### ISSUE TITLE
[Bug]: 无法彻底删除 APIs 上传的 app

### ISSUE THREAD

**Issue by InjoyDeng** [tryzealot/zealot#1445]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

5.2.0

### Git 哈希值 (长度 40)| Git Ref (40 length)

develop

### 反代服务 | Reverse Proxy

无

### HTTPS 证书类型 | HTTPS(SSL)

无 none

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

复现步骤：
1. 删除 docker volumes
2. 重新部署
3. 使用 APIs 上传 App，并且带一个不存在的 channel_key
4. 之后会创建一个新 App，打开该 app，比如：http://localhost:3000/apps/3
5. 点击删除应用
6. 重新进入 http://localhost:3000/apps，服务器报 500

正常情况是调用 `app/controllers/apps_controller.rb:53:in destroy`，但这次删除却是调用的 `app/controllers/schemes_controller.rb:41:in destroy`，这导致没有删除 apps 和 apps_users 表的数据。手动删除 apps 表中的遗留数据后，重复上述步骤不会再复现。

### 问题日志 | Relevant log output

```shell
13:11:34 web.1  | Started DELETE "/apps/3/schemes/5?_method=delete" for 127.0.0.1 at 2024-03-28 13:11:34 +0000
13:11:34 web.1  | Processing by SchemesController#destroy as TURBO_STREAM
13:11:34 web.1  |   Parameters: {"app_id"=>"3", "id"=>"5"}
13:11:35 web.1  |   User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
13:11:35 web.1  |   ↳ app/controllers/application_controller.rb:23:in `set_locale'
13:11:35 web.1  |   Scheme Load (0.6ms)  SELECT "schemes".* FROM "schemes" WHERE "schemes"."id" = $1 ORDER BY "schemes"."id" ASC LIMIT $2  [["id", 5], ["LIMIT", 1]]
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:61:in `set_scheme'
13:11:35 web.1  |   App Load (0.6ms)  SELECT "apps".* FROM "apps" WHERE "apps"."id" = $1 ORDER BY "apps"."id" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:57:in `set_app'
13:11:35 web.1  |   TRANSACTION (1.5ms)  BEGIN
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:35 web.1  |   Channel Load (1.3ms)  SELECT "channels".* FROM "channels" WHERE "channels"."scheme_id" = $1 ORDER BY "channels"."id" ASC  [["scheme_id", 5]]
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:35 web.1  |   Release Load (4.1ms)  SELECT "releases".* FROM "releases" WHERE "releases"."channel_id" = $1  [["channel_id", 12]]
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:35 web.1  |   Metadatum Load (3.4ms)  SELECT "metadata".* FROM "metadata" WHERE "metadata"."release_id" = $1 LIMIT $2  [["release_id", 24], ["LIMIT", 1]]
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:35 web.1  |   Metadatum Destroy (0.9ms)  DELETE FROM "metadata" WHERE "metadata"."id" = $1  [["id", 1]]
13:11:35 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   Release::HABTM_Devices Delete All (2.1ms)  DELETE FROM "devices_releases" WHERE "devices_releases"."release_id" = $1  [["release_id", 24]]
13:11:36 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   Release Destroy (1.9ms)  DELETE FROM "releases" WHERE "releases"."id" = $1  [["id", 24]]
13:11:36 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   Channel::HABTM_WebHooks Delete All (1.9ms)  DELETE FROM "channels_web_hooks" WHERE "channels_web_hooks"."channel_id" = $1  [["channel_id", 12]]
13:11:36 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   Channel Destroy (3.7ms)  DELETE FROM "channels" WHERE "channels"."id" = $1  [["id", 12]]
13:11:36 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   Scheme Destroy (1.5ms)  DELETE FROM "schemes" WHERE "schemes"."id" = $1  [["id", 5]]
13:11:36 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   TRANSACTION (2.3ms)  COMMIT
13:11:36 web.1  |   ↳ app/controllers/schemes_controller.rb:41:in `destroy'
13:11:36 web.1  |   App Load (1.1ms)  SELECT "apps".* FROM "apps" WHERE "apps"."id" = $1 ORDER BY "apps"."id" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]]
13:11:36 web.1  |   ↳ app/models/release.rb:35:in `app'
13:11:36 web.1  | Redirected to http://localhost:3000/apps/3
13:11:36 web.1  | Completed 303 See Other in 1902ms (ActiveRecord: 52.1ms | Allocations: 206614)
```

**Comment by InjoyDeng** [comment]
我测试上传的参数
```
curl --location --request POST 'https://tryzealot.ews.im/api/apps/upload' \
--form 'token="320bacf980e20e7b058be2d77154dc53"' \
--form 'channel_key="channel_key"' \
--form 'release_type="debug"' \
--form 'file=@"~/test.ipa"'
```

**Comment by icyleaf** [comment]
删除应用不会报错的，你是删除了类型才出现的这个问题。原因是当初自以为聪明省三个查询的把最近上传的版本做了缓存，删除下属层级没有删除缓存造成的。
