### ISSUE TITLE
Heroku 创建备份失败

### ISSUE THREAD

**Issue by icyleaf** [tryzealot/zealot#851]
### 部署方式 | How to Deploy

源码部署 | Source

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

none

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

备份功能上线后在 heroku 环境下点击创建备份没有反应。经过查看日志得知：

1. sidekiq 进入队列时间较长。服务没有判断是否在队列
2. sidekiq 运行报错了

### 问题日志 | Relevant log output

```shell
错误类别	Psych::BadAlias
错误消息	Unknown alias: default
错误的回调追踪	/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:430:in `visit_Psych_Nodes_Alias'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `each_slice'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:343:in `revive_hash'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
/app/vendor/ruby-3.1.2/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
```

**Comment by icyleaf** [comment]
上面问题是 psych 4.0 开始做了安全限制，通过扒 rails 的代码通过 c508102d59b632914bfa7409a8699e028851c864 解决，现在遇到其他异常情况：

- redis 连接丢失 `Redis::ConnectionError: Connection lost`
- postgres 链接超时 `pg_dump: error: connection to server at "xxx.amazonaws.com" (174.xx.xx.xx), port 5432 failed: Connection timed out`

**Comment by icyleaf** [comment]
经测试本地，阿里云 及 render 部署都没有问题
